.ORIG x3000
; = = = = = = = = = = = = = = = = =

; MAIN CODE HERE
MAIN_LOOP
LEA R0, FIRST_NUM_PROMPT
PUTS
JSR GETNUM
ST R3, VAR_FIRST_NUM

LEA R0, LINE_BREAK
PUTS

LEA R0, OP_PROMPT
PUTS
JSR GETOP
ST R4, VAR_OP

LEA R0, LINE_BREAK
PUTS

LEA R0, SECOND_NUM_PROMPT
PUTS
JSR GETNUM
ST R3, VAR_SECOND_NUM

LD R0, VAR_FIRST_NUM
LD R1, VAR_OP
LD R2, VAR_SECOND_NUM
JSR CALC
ST R0, RESULT

LEA R0, LINE_BREAK
PUTS

LEA R0, RESULT_PROMPT
PUTS
LD R0, RESULT
JSR DISPLAY

LEA R0, LINE_BREAK
PUTS

BR MAIN_LOOP
; - - - - - - - - - - - - - - - - -

; MAIN VARS
FIRST_NUM_PROMPT .STRINGZ "Enter first number (0 - 99): "
SECOND_NUM_PROMPT .STRINGZ "Enter second number (0 - 99): "
OP_PROMPT  .STRINGZ "Enter an operation (+, -, *): "
LINE_BREAK .STRINGZ "\n"
RESULT_PROMPT .STRINGZ "Result: "

VAR_FIRST_NUM .FILL #0
VAR_SECOND_NUM .FILL #0
VAR_OP .FILL #0
RESULT .FILL #0

; = = = = = = = = = = = = = = = = =

; = = = = = = = = = = = = = = = = =
DISPLAY
ST R7, SAVE_R7_DISPLAY
; DISPLAY CODE HERE

ADD R1, R0, #0
BRnp DISPLAY_SIGN
LD R0, DISPLAY_0
OUT
BR  DISPLAY_RET

DISPLAY_SIGN
BRzp DISPLAY_ABSOLUTE
LD R0, DISPLAY_MINUS
OUT

NOT R1, R1
ADD R1, R1, #1


DISPLAY_ABSOLUTE
LEA R2, DISPLAY_DIV
LD R3, DISPLAY_COUNT
AND R4, R4, #0

DISPLAY_LOOP
LDR R5, R2, #0
AND R0, R0, #0


DISPLAY_SUBTRACT
NOT R6, R5
ADD R6, R6, #1
ADD R7, R1, R6
BRn DISPLAY_MAKE
ADD R1, R7, #0
ADD R0, R0, #1
BR DISPLAY_SUBTRACT


DISPLAY_MAKE

ADD R6, R0, #0
BRp DISPLAY_PRINT

ADD R6, R4, #0
BRp DISPLAY_PRINTs

ADD R6, R5, #-1
BRnp DISPLAY_NEXT

DISPLAY_PRINT
LD R6, DISPLAY_0
ADD R0, R6, R0
OUT

ADD R4, R4, #1
DISPLAY_NEXT
ADD R2, R2, #1
ADD R3, R3, #-1
BRp DISPLAY_LOOP

DISPLAY_RET

LD R7, SAVE_R7_DISPLAY
RET


; - - - - - - - - - - - - - - - - -
; DISPLAY VARS

DISPLAY_DIV .FILL #1000
            .FILL #100
            .FILL #10
            .FILL #1
DISPLAY_COUNT .FILL #4
DISPLAY_0 .FILL x0030
DISPLAY_MINUS .FILL x002D
SAVE_R7_DISPLAY .FILL #0

; = = = = = = = = = = = = = = = = =

; = = = = = = = = = = = = = = = = =
GETNUM
ST R7, SAVE_R7_GETNUM
; GETNUM CODE HERE
AND R3, R3, #0

GETNUM_LOOP
GETC
ADD R1, R0, #-13    
BRz GETNUM_DONE
ADD R1, R0, #-10
BRz GETNUM_DONE
OUT 
ADD R0, R0, #-16
ADD R0, R0, #-16
ADD R0, R0, #-16
ADD R5,R3,#0
ADD R3,R3,R3      
ADD R3,R3,R3     
ADD R3,R3,R3       
ADD R3,R3,R5      
ADD R3,R3,R5      
ADD R3,R3,R0
BR GETNUM_LOOP

GETNUM_DONE

LD R7, SAVE_R7_GETNUM
RET
; - - - - - - - - - - - - - - - - -
; GETNUM VARS
TEST .STRINGZ "TEST"
SAVE_R7_GETNUM .FILL #0
; = = = = = = = = = = = = = = = = =

; = = = = = = = = = = = = = = = = =
GETOP
ST R7, SAVE_R7_GETOP
; GETOP CODE HERE

GETOP_LOOP
GETC
LD R6, GETOP_NEGATIVE_PLUS
ADD R5, R0, R6
BRz GETOP_DONE

LD R6, GETOP_NEGATIVE_MINUS
ADD R5, R0, R6
BRz GETOP_DONE

LD R6, GETOP_NEGATIVE_MULT
ADD R5, R0, R6
BRz GETOP_DONE


BR GETOP_LOOP

GETOP_DONE
OUT
ADD R4, R0, #0 


LD R7, SAVE_R7_GETOP
RET
; - - - - - - - - - - - - - - - - -
; GETOP VARS
GETOP_NEGATIVE_PLUS .FILL #-43
GETOP_NEGATIVE_MINUS .FILL #-45
GETOP_NEGATIVE_MULT .FILL #-42
SAVE_R7_GETOP .FILL #0
; = = = = = = = = = = = = = = = = =

; = = = = = = = = = = = = = = = = =
CALC
ST R7, SAVE_R7_CALC
; CALC CODE HERE

LD R6, CALC_NEGATIVE_PLUS
ADD  R5, R4, R6
BRz  CALC_PLUS

LD R6, CALC_NEGATIVE_MINUS
ADD  R5, R4, R6
BRz  CALC_MINUS

LD R6, CALC_NEGATIVE_MULT
ADD  R5, R4, R6
BRz  CALC_MULT

CALC_PLUS
ADD R0, R0, R2
RET

CALC_MINUS
NOT R2, R2
ADD R2, R2, #1
ADD R0, R0, R2
RET

CALC_MULT
AND R3, R3, #0      ; clear accumulator
ADD R5, R0, #0      ; multiplicand (first operand)
ADD R1, R2, #0      ; counter = second operand
BRz CALC_DONE       ; if second operand is zero, result is 0

CALC_MULT_LOOP
ADD  R3, R3, R5     ; accumulate multiplicand
ADD  R1, R1, #-1    ; decrement counter
BRp  CALC_MULT_LOOP

CALC_DONE
ADD R0, R3, #0

LD R7, SAVE_R7_CALC
RET

; - - - - - - - - - - - - - - - - -
; CALC VARS
CALC_NEGATIVE_PLUS .FILL #-43
CALC_NEGATIVE_MINUS .FILL #-45
CALC_NEGATIVE_MULT .FILL #-42
SAVE_R7_CALC .FILL #0
; = = = = = = = = = = = = = = = = =

.END